# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    cache: ~
    job_min_image:
      quality: 85
      filters:
        thumbnail:
          size: [80, 80]
          mode: outbound
    blog_image:
      cache: ~
      quality: 85
      filters:
        thumbnail:
          size: [1267, 767]
          mode: outbound
    job_signe_image:
      cache: ~
      quality: 85
      filters:
        thumbnail:
          size: [1260, 787]
          mode: outbound
    # blog_page_category_image:
    #   cache: ~
    #   quality: 85
    #   filters:
    #     thumbnail:
    #       size: [1260, 787]
    #       mode: outbound
