sonata_seo:
  encoding: UTF-8
  page:
    title: "capital rh solutions"
    #title_prefix:  'Prefix |'
    default: sonata.seo.page.default
    metas:
      name:
        keywords: capital rh solutions, cameroun, rh, emplois, jobs, boulot, recherche d'emplois, salarié, recrutement
        robots: index, follow

      property:
        # Facebook application settings
        "fb:app_id": "389898079878693"
        "fb:admins": "logonedigital"

        # Open Graph information
        # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
        "og:site_name": capital rh solutions

      http-equiv:
        "Content-Type": text/html; charset=utf-8
        #'X-Ua-Compatible':      IE=EmulateIE7

      charset:
        UTF-8: ""

    head:
      "xmlns": http://www.w3.org/1999/xhtml
      "xmlns:og": http://opengraphprotocol.org/schema/
      #'xmlns:fb':           "http://www.facebook.com/2008/fbml"
